FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    git \
    sudo \
    wget \
    iproute2 \
    python3 \
    golang-go \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/redcanaryco/atomic-red-team.git /opt/atomic-red-team

ENV GOPATH=$HOME/go
ENV PATH=$PATH:$GOPATH/bin

RUN go install github.com/redcanaryco/go-atomicredteam/cmd/goart@latest

WORKDIR /opt/atomic-red-team/atomics