apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-cap-sys-admin"
spec:
  kprobes:
  - call: "cap_capable"
    syscall: false
    args:
    - index: 0
      type: "cred"
    - index: 1
      type: "user_namespace"
    - index: 2
      type: "int"
    selectors:
    - matchArgs:
      - index: 2
        operator: "Equal"
        values:
        - "21" # CAP_SYS_ADMIN