apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-tcp-connect"
spec:
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
      - matchPIDs:
          - isNamespacePID: true
            operator: "NotIn"
            values: [0, 1]