FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    curl \
    git \
    sudo \
    wget \
    iproute2 \
    python3 \
    golang-go \
    make \
    unzip \
    && rm -rf /var/lib/apt/lists/*

ENV GOPATH=$HOME/go
ENV PATH=$PATH:$GOPATH/bin

RUN git clone https://github.com/activeshadow/go-atomicredteam.git /goart && cd /goart && make bin/goart
ENV PATH=$PATH:/goart/bin

CMD ["goart"]