FROM alpine:latest

RUN apk add --no-cache \
    bash \
    curl \
    git \
    sudo \
    wget \
    iproute2 \
    python3 \
    go \
    make \
    unzip

ENV GOPATH=$HOME/go
ENV PATH=$PATH:$GOPATH/bin

RUN git clone https://github.com/activeshadow/go-atomicredteam.git /goart && cd /goart && make bin/goart
ENV PATH=$PATH:/goart/bin

CMD ["goart"]