FROM alpine:latest AS builder

RUN apk add --no-cache \
    git \
    go \
    make

RUN git clone https://github.com/activeshadow/go-atomicredteam.git /goart && \
    cd /goart && \
    make bin/goart

FROM alpine:latest

RUN apk add --no-cache \
    bash \
    curl \
    sudo \
    wget \
    iproute2 \
    python3 \
    unzip

COPY --from=builder /goart/bin/goart /usr/local/bin/goart

CMD ["goart"]
