# Detect WRITE in selected directories (/bin/, /usr/bin/, /sbin/)
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-bin-write"
spec:
  kprobes:
  - call: "security_file_permission"
    syscall: false
    args:
    - index: 0
      type: "file" 
    - index: 1
      type: "int"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/bin/"
        - "/usr/bin/"
        - "/sbin/"
      - index: 1
        operator: "Equal"
        values:
        - "2" # 0x02 = MAY_WRITE